services:

  build:
    image: oscarmlage/hugo:v0.160.1-node
    build:
      context: .
      dockerfile: Dockerfile.hugo
    command: build
    working_dir: /src
    volumes:
      - "${PWD}/src:/src"

  serve:
    image: oscarmlage/hugo:v0.160.1-node
    build:
      context: .
      dockerfile: Dockerfile.hugo
    command: server --bind 0.0.0.0 --port 1313
    working_dir: /src
    volumes:
      - "${PWD}/src:/src"
    ports:
      - 1313:1313
    stdin_open: true # -i
    tty: true # -t
