baseURL: 'https://oscarmlage.com'
languageCode: 'en-us'
title: 'oscarmlage'
theme:
  - 'oscar'
  - 'hugo-shortcode-gallery'
pygmentsStyle: "monokai"
canonifyurls: true
paginate: 10
summarylength: 30

timeout: 60000
params:
  galleryLoadJQuery: true

defaultContentLanguage: "en"

markup:
  goldmark:
    renderer:
      unsafe: true

author:
  name: "oscarmlage"

taxonomies:
  tag: "tags"

permalinks:
  sections: "/:slug/"

menu:
  main:
    - identifier: "posts"
      name: "Posts"
      title: "Posts"
      url: "/posts/"
      weight: 10
    - identifier: "Log"
      name: "Log"
      title: "Log"
      url: "/microposts/"
      weight: 20
    - identifier: "medialog"
      name: "Medialog"
      title: "Medialog"
      url: "/medialog/"
      weight: 20
    - identifier: "archive"
      name: "Archive"
      title: "Archive"
      url: "/archive/"
      weight: 30
    - identifier: "about"
      name: "About"
      title: "About"
      url: "/about/"
      weight: 40
